### ISSUE TITLE
Revisar permisos del directorio uploads

### ISSUE THREAD

**Issue by chimilord** [chimilord/unus-se#1]
Cuando intentan agregar un avatar (el cual se sube al dir /uploads) para persona la aplicación no lo puede subir. Pasa en ambiente de producción y de test en el server, local no.

**Comment by tomytree22** [comment]
LMAO

**Comment by tomytree22** [comment]
@ismaelhz please take a look ASAP, thanks for your report @chimilord

**Comment by ismaelhz** [comment]
Se cambiaron los permisos de todo el directorio unus-se a www-data, tanto usuario como grupo en ambos ambientes (producción y dev).

Se puede considerar algún script que actualice el proyecto y verifique que los archivos tengan el usuario correcto, algo como esto funcionaría (si es que ya quedó):

cd ruta/unus-se
sudo git pull
sudo chown -R www-data:www-data unus-se

**Comment by chimilord** [comment]
@tomytree22 Agregó un cambio a PersonController para arreglar el edit.
